# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 30c866a0e120e8e6b096e3d7802f7e8a2c6398a2b7a287d3bd70c3505092f3d247a24e7e0a566b689bfb159638bdb631cd7d9d0ef709c53aafc00cab0c43826f

test:
  secret_key_base: e8c9fbaf0ded210ebfab718bb2faeb294a0128144069be0cbd05d1e269a73190f209133163fe6204a6387557fcec2caa114f0abda19909fff1f3ca9152b96b0e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
